/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Clases.ClsClientes;
import Clases.ClsConductores;
import Clases.ClsEnvios;
import Clases.ClsGlobales;
import Clases.ClsVehiculos;
import DB.ClsDB;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class FrmAgregarEnvio extends javax.swing.JFrame {
    
    ClsEnvios MisEnvios = new ClsEnvios();
    public int IdEditar = -1;
    
    public String strCliente = "";
    public String strConductor = "";
    public String strPlaca = "";
    
    /**
     * Creates new form FrmAgregarEnvio
     */
    public FrmAgregarEnvio() {
        initComponents();
    }
    
    private boolean ValidarDatos(){
        
        boolean Validado = true;
        
        if (txtDireccion.getText().isEmpty() ||
            cmbCliente.getSelectedIndex() == 0 ||
            cmbConductor.getSelectedIndex() == 0 ||
            Integer.parseInt(txtCosto.getValue().toString()) <= 0
            ) 
        {
            Validado = false;
        }
        
        return Validado;
    }
    
    private void Limpiar(){
        txtDireccion.setText("");
        cmbCliente.setSelectedIndex(0);
        cmbConductor.setSelectedIndex(0);
        txtCosto.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBarraSup = new javax.swing.JLabel();
        pnlCuerpo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidos = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cmbConductor = new javax.swing.JComboBox<>();
        lblCedula1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        lblNombre1 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        txtCosto = new javax.swing.JSpinner();
        cmbVehiculo = new javax.swing.JComboBox<>();
        lblApellidos1 = new javax.swing.JLabel();
        chkEntregado = new javax.swing.JCheckBox();
        chkRecibido = new javax.swing.JCheckBox();
        chkEnviado = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar un nuevo envío");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitulo.setForeground(java.awt.SystemColor.control);
        lblTitulo.setText("Envío de paquetería");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblBarraSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazul.jpg"))); // NOI18N
        getContentPane().add(lblBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));

        pnlCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCuerpo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 472, 10));

        lblApellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Conductor");
        pnlCuerpo.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Costo de envío");
        pnlCuerpo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        pnlCuerpo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 472, 10));

        btnCerrar.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCerrar.setForeground(java.awt.SystemColor.control);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setActionCommand("");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlCuerpo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 40));

        btnLimpiar.setBackground(new java.awt.Color(51, 51, 51));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnLimpiar.setForeground(java.awt.SystemColor.control);
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setActionCommand("");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlCuerpo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, 40));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnGuardar.setForeground(java.awt.SystemColor.control);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        btnGuardar.setText("GUARDAR CLIENTE");
        btnGuardar.setActionCommand("");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlCuerpo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 191, 40));

        cmbConductor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbConductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un conductor" }));
        pnlCuerpo.add(cmbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 150, 30));

        lblCedula1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCedula1.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula1.setText("Dirección de entrega");
        pnlCuerpo.add(lblCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane2.setViewportView(txtDireccion);

        pnlCuerpo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 480, 70));

        lblNombre1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre1.setText("Cliente");
        pnlCuerpo.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cmbCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente" }));
        pnlCuerpo.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        txtCosto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pnlCuerpo.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, 40));

        cmbVehiculo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un vehículo" }));
        pnlCuerpo.add(cmbVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, 30));

        lblApellidos1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos1.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos1.setText("Vehículo");
        pnlCuerpo.add(lblApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        chkEntregado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkEntregado.setText("Paquete entregado");
        pnlCuerpo.add(chkEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 140, -1));

        chkRecibido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkRecibido.setSelected(true);
        chkRecibido.setText("Paquete recibido");
        pnlCuerpo.add(chkRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));

        chkEnviado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkEnviado.setText("Paquete enviado");
        pnlCuerpo.add(chkEnviado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, -1));
        pnlCuerpo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 472, 10));

        getContentPane().add(pnlCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 520, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        this.setAlwaysOnTop(false);

        if (ValidarDatos()) {

            if (IdEditar > -1) {

                ClsDB.jsonEnvios.get(IdEditar).Direccion = txtDireccion.getText();
                ClsDB.jsonEnvios.get(IdEditar).Monto = Integer.parseInt(txtCosto.getValue().toString());
                
                ClsDB.jsonEnvios.get(IdEditar).Recibido = chkRecibido.isSelected();
                ClsDB.jsonEnvios.get(IdEditar).Enviado = chkEnviado.isSelected();
                ClsDB.jsonEnvios.get(IdEditar).Entregado = chkEntregado.isSelected();
                        
                ClsDB.jsonEnvios.get(IdEditar).MiCliente.clear();
                ClsDB.jsonEnvios.get(IdEditar).MiConductor.clear();
                ClsDB.jsonEnvios.get(IdEditar).MiVehiculo.clear();
                
                ClsDB.jsonEnvios.get(IdEditar).MiCliente.add(ClsDB.jsonClientes.get(cmbCliente.getSelectedIndex()-1));
                ClsDB.jsonEnvios.get(IdEditar).MiConductor.add(ClsDB.jsonConductores.get(cmbConductor.getSelectedIndex()-1));
                ClsDB.jsonEnvios.get(IdEditar).MiVehiculo.add(ClsDB.jsonVehiculos.get(cmbVehiculo.getSelectedIndex() -1));
                
            }else{
                MisEnvios.IdEnvio = ClsDB.jsonEnvios.size() + 1;
                MisEnvios.Direccion = txtDireccion.getText();
                MisEnvios.Monto = Integer.parseInt(txtCosto.getValue().toString());
                
                MisEnvios.Recibido = chkRecibido.isSelected();
                MisEnvios.Enviado = chkEnviado.isSelected();
                MisEnvios.Entregado = chkEntregado.isSelected();
                
                MisEnvios.MiCliente.add(ClsDB.jsonClientes.get(cmbCliente.getSelectedIndex()-1));
                MisEnvios.MiConductor.add(ClsDB.jsonConductores.get(cmbConductor.getSelectedIndex()-1));
                MisEnvios.MiVehiculo.add(ClsDB.jsonVehiculos.get(cmbVehiculo.getSelectedIndex()-1));

                ClsDB.jsonEnvios.add(MisEnvios);
            }

            if (MisEnvios.GuardarDatosMemoria()) {

                JOptionPane.showMessageDialog(null,
                    "Los datos del cliente se han guardado con éxito",
                    "Proceso exitoso",
                    JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
            }

        }else{
            JOptionPane.showMessageDialog(null,
                "Por favor ingrese toda la información solicitada",
                "Error de datos",
                JOptionPane.ERROR_MESSAGE);
            this.setAlwaysOnTop(true);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ClsGlobales.fEnvios.IdEditar = 0;
        ClsGlobales.fEnvios.LlenarLista("");
        ClsGlobales.formPrincipal.enable(true);
        ClsGlobales.formPrincipal.show();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        cmbCliente.removeAllItems();
        cmbCliente.addItem("Seleccione un cliente");
        for (ClsClientes MiCliente : ClsDB.jsonClientes) {
            cmbCliente.addItem(MiCliente.Nombre + " " + MiCliente.Apellidos);
        }
        
        if (!strCliente.equals("")) {
            cmbCliente.setSelectedItem(strCliente);
        }
        
        cmbConductor.removeAllItems();
        cmbConductor.addItem("Seleccione un conductor");
        for (ClsConductores MiConductor : ClsDB.jsonConductores) {
            cmbConductor.addItem(MiConductor.Nombre + " " + MiConductor.Apellidos);
        }
        
        if (!strConductor.equals("")) {
            cmbConductor.setSelectedItem(strConductor);
        }
        
        cmbVehiculo.removeAllItems();
        cmbVehiculo.addItem("Seleccione un vehículo");
        for (ClsVehiculos MiVehiculo : ClsDB.jsonVehiculos) {
            cmbVehiculo.addItem(MiVehiculo.Placa);
        }
        
        if (!strPlaca.equals("")) {
            cmbVehiculo.setSelectedItem(strPlaca);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JCheckBox chkEntregado;
    public javax.swing.JCheckBox chkEnviado;
    public javax.swing.JCheckBox chkRecibido;
    public javax.swing.JComboBox<String> cmbCliente;
    public javax.swing.JComboBox<String> cmbConductor;
    public javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblBarraSup;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCuerpo;
    public javax.swing.JSpinner txtCosto;
    public javax.swing.JTextArea txtDireccion;
    // End of variables declaration//GEN-END:variables
}
