/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms;

import Clases.ClsEnvios;
import Clases.ClsGlobales;
import DB.ClsDB;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juand
 */
public class FrmEnvios extends javax.swing.JInternalFrame {

    ClsEnvios MisEnvios = new ClsEnvios();
    FrmAgregarEnvio fAgregarEnvios = new FrmAgregarEnvio();
    
    public int IdEditar = -1;
    /**
     * Creates new form FrmEnvios
     */
    public FrmEnvios() {
        initComponents();
        MisEnvios.ObtenerDatosMemoria();
        LlenarLista("");
    }
    
    public void LlenarLista(String buscar){
        
        DefaultTableModel modelo = (DefaultTableModel) tblEnvios.getModel();
        
        modelo.setRowCount(0);
        
        for (ClsEnvios MiEnvio : ClsDB.jsonEnvios) {
            
            boolean Bandera = true;
            
            if (chkPendientes.isSelected() && 
                MiEnvio.Entregado) {
                Bandera = false;
            }
            
            if (Bandera) {
                Object[] row = new Object[]{MiEnvio.IdEnvio,
                                        MiEnvio.Direccion,
                                        MiEnvio.MiCliente.get(0).Nombre + " " + MiEnvio.MiCliente.get(0).Apellidos,
                                        MiEnvio.MiCliente.get(0).Telefono,
                                        MiEnvio.MiConductor.get(0).Nombre + " " + MiEnvio.MiConductor.get(0).Apellidos,
                                        MiEnvio.MiVehiculo.get(0).Placa,
                                        MiEnvio.MiConductor.get(0).Telefono,
                                        MiEnvio.Recibido,
                                        MiEnvio.Enviado,
                                        MiEnvio.Entregado};
            
                if (buscar.equals("")) {
                    modelo.addRow(row);
                }else if (MiEnvio.Direccion.toLowerCase().contains(buscar) ||
                          MiEnvio.MiCliente.get(0).Nombre.toLowerCase().contains(buscar) ||
                          MiEnvio.MiCliente.get(0).Telefono.toLowerCase().contains(buscar) ||
                          MiEnvio.MiConductor.get(0).Nombre.toLowerCase().contains(buscar) ||
                          MiEnvio.MiConductor.get(0).Telefono.toLowerCase().contains(buscar)) {
                          modelo.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnvios = new javax.swing.JTable();
        chkPendientes = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Lista de envíos");

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar un nuevo envío");
        btnAgregar.setToolTipText("");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Buscar envío");

        btnEditar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar envío seleccionado");
        btnEditar.setToolTipText("");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tblEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dirección", "Cliente", "Teléfono", "Conductor", "Placa", "Teléfono", "Recibido", "Enviado", "Entregado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnvios.setRowHeight(25);
        tblEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnviosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnvios);
        if (tblEnvios.getColumnModel().getColumnCount() > 0) {
            tblEnvios.getColumnModel().getColumn(0).setMinWidth(40);
            tblEnvios.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblEnvios.getColumnModel().getColumn(0).setMaxWidth(40);
            tblEnvios.getColumnModel().getColumn(7).setMinWidth(60);
            tblEnvios.getColumnModel().getColumn(7).setPreferredWidth(60);
            tblEnvios.getColumnModel().getColumn(7).setMaxWidth(60);
            tblEnvios.getColumnModel().getColumn(8).setMinWidth(60);
            tblEnvios.getColumnModel().getColumn(8).setPreferredWidth(60);
            tblEnvios.getColumnModel().getColumn(8).setMaxWidth(60);
            tblEnvios.getColumnModel().getColumn(9).setMinWidth(60);
            tblEnvios.getColumnModel().getColumn(9).setPreferredWidth(60);
            tblEnvios.getColumnModel().getColumn(9).setMaxWidth(60);
        }

        chkPendientes.setSelected(true);
        chkPendientes.setText("Mostrar solo los pendientes");
        chkPendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkPendientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkPendientes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (!fAgregarEnvios.isShowing()) {

            IdEditar = -1;
            fAgregarEnvios.IdEditar = -1;
            fAgregarEnvios.txtDireccion.setText("");
            fAgregarEnvios.chkRecibido.setSelected(true);
            fAgregarEnvios.chkEnviado.setSelected(false);
            fAgregarEnvios.chkEntregado.setSelected(false);
            fAgregarEnvios.cmbCliente.setSelectedIndex(0);
            fAgregarEnvios.cmbConductor.setSelectedIndex(0);
            fAgregarEnvios.btnGuardar.setText("GUARDAR ENVIO");

            fAgregarEnvios.show();
            ClsGlobales.formPrincipal.enable(false);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        LlenarLista(txtBuscar.getText().toLowerCase());
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (IdEditar > 0 && IdEditar <= ClsDB.jsonEnvios.size()) {

            if (!fAgregarEnvios.isShowing()) {

                int Contador = 0;

                for (ClsEnvios MiEnvio : ClsDB.jsonEnvios) {
                    if (MiEnvio.IdEnvio == IdEditar) {
                        IdEditar = Contador;
                        break;
                    }
                    Contador++;
                }

                fAgregarEnvios.IdEditar = IdEditar;

                fAgregarEnvios.txtDireccion.setText(ClsDB.jsonEnvios.get(IdEditar).Direccion);
                fAgregarEnvios.txtCosto.setValue(ClsDB.jsonEnvios.get(IdEditar).Monto);
                fAgregarEnvios.chkRecibido.setSelected(ClsDB.jsonEnvios.get(IdEditar).Recibido);
                fAgregarEnvios.chkEnviado.setSelected(ClsDB.jsonEnvios.get(IdEditar).Enviado);
                fAgregarEnvios.chkEntregado.setSelected(ClsDB.jsonEnvios.get(IdEditar).Entregado);
                
                fAgregarEnvios.btnGuardar.setText("EDITAR ENVIO");

                fAgregarEnvios.strCliente = ClsDB.jsonEnvios.get(IdEditar).MiCliente.get(0).Nombre + " " + ClsDB.jsonEnvios.get(IdEditar).MiCliente.get(0).Apellidos;
                fAgregarEnvios.strConductor = ClsDB.jsonEnvios.get(IdEditar).MiConductor.get(0).Nombre + " " + ClsDB.jsonEnvios.get(IdEditar).MiConductor.get(0).Apellidos;
                fAgregarEnvios.strPlaca = ClsDB.jsonEnvios.get(IdEditar).MiVehiculo.get(0).Placa;
                
                fAgregarEnvios.show();
                ClsGlobales.formPrincipal.enable(false);
            }

        }else{
            JOptionPane.showMessageDialog(null,
                "Por favor seleccione un cliente para editar",
                "Editar",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnviosMouseClicked
        int fila = evt.getY()/tblEnvios.getRowHeight();
        IdEditar =  Integer.parseInt(tblEnvios.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tblEnviosMouseClicked

    private void chkPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkPendientesMouseClicked
        LlenarLista(txtBuscar.getText().toLowerCase());
    }//GEN-LAST:event_chkPendientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JCheckBox chkPendientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnvios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
