/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Clases.ClsAcceso;
import DB.ClsDB;
import Clases.ClsGlobales;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class FrmLogin extends javax.swing.JFrame {
    
    ClsAcceso MiAcceso = new ClsAcceso();
    FrmRegistro fRegistro = new FrmRegistro();
    FrmOlvido fOlvido = new FrmOlvido();
    
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        MiAcceso.ObtenerDatosMemoria();
        
        for (int i = 0; i < ClsDB.jsonAcceso.size(); i++) {
            if (ClsDB.jsonAcceso.get(i).Recordar) {
                this.txtCorreo.setText(ClsDB.jsonAcceso.get(i).Correo);
                this.txtClave.setText(ClsDB.jsonAcceso.get(i).Clave);
                this.chkRecordar.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        chkRecordar = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        lblOlvido = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al sistema");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar.png"))); // NOI18N
        getContentPane().add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo electrónico");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txtCorreo.setBackground(java.awt.SystemColor.control);
        txtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, 40));

        lblClave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblClave.setForeground(new java.awt.Color(0, 0, 0));
        lblClave.setText("Clave de acceso");
        getContentPane().add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        txtClave.setBackground(java.awt.SystemColor.control);
        txtClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setAlignmentX(1.5F);
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 40));

        chkRecordar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkRecordar.setForeground(new java.awt.Color(0, 0, 0));
        chkRecordar.setText("Recordar mis credenciales");
        getContentPane().add(chkRecordar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(0, 0, 102));
        btnIngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnIngresar.setForeground(java.awt.SystemColor.control);
        btnIngresar.setText("INGRESAR AL SISTEMA");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 240, 40));

        lblOlvido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblOlvido.setForeground(new java.awt.Color(0, 51, 255));
        lblOlvido.setText("¿Olvidó su contraseña?");
        lblOlvido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvidoMouseClicked(evt);
            }
        });
        getContentPane().add(lblOlvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        lblCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblCuenta.setText("¿Aún no tienes cuenta?");
        getContentPane().add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        btnRegistro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRegistro.setText("Regístrate aquí");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 160, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        
        if (fRegistro != null) {
            fRegistro.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        MiAcceso.Correo = txtCorreo.getText();
        MiAcceso.Clave = txtClave.getText();
        MiAcceso.Recordar = chkRecordar.isSelected();
        
        if (ClsGlobales.ValidarMail(txtCorreo.getText())) 
        {
            if (MiAcceso.ConsultarAcceso(MiAcceso.Correo, MiAcceso.Clave)) {
            
                for (ClsAcceso MiObjeto : ClsDB.jsonAcceso)
                {
                    if (MiObjeto.Correo.equals(MiAcceso.Correo)) {
                        MiObjeto.Recordar = MiAcceso.Recordar;
                    }else{
                        MiObjeto.Recordar = false;
                    }
                }

                MiAcceso.GuardarDatosMemoria();
                
                ClsGlobales.formPrincipal.show();
                
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(null,
                "La información de acceso es incorrecta", "Error de validación",
                JOptionPane.ERROR_MESSAGE
                );
            }
        }else{
            JOptionPane.showMessageDialog(null,
            "Por favor ingrese un correo electrónico válido", "Error de validación",
            JOptionPane.ERROR_MESSAGE
            );
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void lblOlvidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidoMouseClicked
        
        if (fOlvido != null) {
            fOlvido.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_lblOlvidoMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JCheckBox chkRecordar;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblOlvido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
