/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import Clases.ClsAcceso;
import Clases.ClsGlobales;
import DB.ClsDB;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class FrmRegistro extends javax.swing.JFrame {
    
    ClsAcceso MiDataAcceso = new ClsAcceso();
    
    /**
     * Creates new form Registro
     */
    public FrmRegistro() {
        initComponents();
    }
    
    private boolean ValidarCampos(){
        
        boolean Aplicar = true;
        
        if (txtCorreo.getText().equals("") ||
            txtClave.getText().equals("")) {
            Aplicar = false;
        }
        
        return Aplicar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnGuardarAcceso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de acceso");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo electrónico");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 144, -1, -1));

        txtCorreo.setBackground(java.awt.SystemColor.control);
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 164, 230, 40));

        lblClave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblClave.setForeground(new java.awt.Color(0, 0, 0));
        lblClave.setText("Contraseña de acceso");
        getContentPane().add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 214, -1, -1));

        txtClave.setBackground(java.awt.SystemColor.control);
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 234, 230, 40));

        btnGuardarAcceso.setBackground(new java.awt.Color(0, 0, 102));
        btnGuardarAcceso.setForeground(java.awt.SystemColor.control);
        btnGuardarAcceso.setText("GUARDAR ACCESO");
        btnGuardarAcceso.setActionCommand("");
        btnGuardarAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAccesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 292, 230, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.control);
        jLabel2.setText("Regístro de usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazul.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnGuardarAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAccesoActionPerformed
        
        MiDataAcceso.Correo = txtCorreo.getText();
        MiDataAcceso.Clave = txtClave.getText();
        MiDataAcceso.Recordar = false;
        MiDataAcceso.Activo = false;
        MiDataAcceso.IdAcceso = ClsDB.jsonAcceso.size() + 1;
        
        if (ClsDB.jsonAcceso.isEmpty()) {
            MiDataAcceso.Activo = true;
        }
        
        boolean Existe = false;
        
        for (ClsAcceso MiObjeto : ClsDB.jsonAcceso) 
        {
            if (MiObjeto.Correo.toLowerCase().equals(txtCorreo.getText().toLowerCase())) {
                Existe = true;
                break;
            }
        }
        
        boolean EmailValidado = false;
        
        if (ClsGlobales.ValidarMail(txtCorreo.getText())) {
            EmailValidado = true;
        }
        
        if (ValidarCampos() && !Existe && EmailValidado) {

            ClsDB.jsonAcceso.add(MiDataAcceso);

            if (!MiDataAcceso.GuardarDatosMemoria()) {
                JOptionPane.showMessageDialog(null,
                    "No se logró guardar la información", "Error de validación",
                    JOptionPane.ERROR_MESSAGE
                );
            }else{
                JOptionPane.showMessageDialog(null,
                    "Datos de ingreso guardados", "Proceso finalizado",
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                this.dispose();
            }
        }
        else{
            if (!EmailValidado) {
                JOptionPane.showMessageDialog(null,
                    "Por favor ingrese un correo electrónico válido", "Error de datos",
                    JOptionPane.ERROR_MESSAGE
                );
            }else if (!Existe) {
                JOptionPane.showMessageDialog(null,
                    "Debe ingresar todos los datos solicitados", "Error de datos",
                    JOptionPane.ERROR_MESSAGE
                );
            }else{
                JOptionPane.showMessageDialog(null,
                    "Este correo ya se encuentra registrado", "Error de datos",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnGuardarAccesoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        FrmLogin fLogin = new FrmLogin();
        fLogin.show();
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
