/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms;

import Clases.ClsAcceso;
import DB.ClsDB;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author juand
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {
    
    ClsAcceso MisAccesos = new ClsAcceso();
    
    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
        LlenarLista();
    }
    
    public void LlenarLista(){
        
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        
        modelo.setRowCount(0);
        
        for (ClsAcceso MiAcceso : ClsDB.jsonAcceso) {
            Object[] row = new Object[]{MiAcceso.Activo,MiAcceso.Correo};
            modelo.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();

        setBorder(null);

        tblUsuarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activo", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.setRowHeight(25);
        tblUsuarios.setRowSelectionAllowed(false);
        tblUsuarios.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMinWidth(60);
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(60);
            tblUsuarios.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Lista de accesos al sistema");

        btnRefrescar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abajo.png"))); // NOI18N
        btnRefrescar.setText("Refrescar la lista");
        btnRefrescar.setToolTipText("");
        btnRefrescar.setBorder(null);
        btnRefrescar.setBorderPainted(false);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefrescar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
        int columna = tblUsuarios.getColumnModel().getColumnIndexAtX(evt.getX());
        int fila = evt.getY()/tblUsuarios.getRowHeight();
        
        if (columna == 0) {
            
            if (fila > 0) {
                
                String Estado = "ACTIVAR";

                if (ClsDB.jsonAcceso.get(fila).Activo) {
                    Estado = "DESACTIVAR";
                }

                int resultado = JOptionPane.showConfirmDialog(null, "Esta seguro que desea " + Estado + " al usuario: " + ClsDB.jsonAcceso.get(fila).Correo, "Cambiar estado de usuario", JOptionPane.YES_NO_OPTION);

                if (resultado == JOptionPane.YES_OPTION) {

                    ClsDB.jsonAcceso.get(fila).Activo = !ClsDB.jsonAcceso.get(fila).Activo;
                    MisAccesos.GuardarDatosMemoria();

                }
                
            }else{
                JOptionPane.showMessageDialog(null, 
                        "El usuario administrador no puede ser eliminado", 
                         "Error de datos", 
                         JOptionPane.ERROR_MESSAGE);
            }
            
            LlenarLista();
        }
        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        LlenarLista();
    }//GEN-LAST:event_btnRefrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
